import json
import os
import streamlit as st
from datetime import datetime

# --- 配置区 ---
# 1. 数据存储文件
DB_FILE = "news_database.json"

# 2. Obsidian 仓库路径 (需要修改为你电脑上的真实路径!)
# 例如: "/Users/zhanghao/yangyun/Code_projects/obsidian_notes/养云协作/决策归档"
OBSIDIAN_PATH = "/Users/zhanghao/yangyun/Code_projects/obsidian_notes" 

# --- 功能 1: 加载/保存雷达数据 ---
def load_data():
    """从本地 JSON 文件加载数据，如果不存在则返回默认空列表"""
    if os.path.exists(DB_FILE):
        with open(DB_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    return [] # 返回空列表，等待初始化

def save_data(news_list):
    """把雷达数据保存到本地 JSON"""
    with open(DB_FILE, "w", encoding="utf-8") as f:
        json.dump(news_list, f, ensure_ascii=False, indent=4)

# --- 功能 2: 导出决策到 Obsidian ---
def save_to_obsidian(case_data, decision_note):
    """
    生成 Markdown 文件并写入 Obsidian 文件夹
    """
    # 1. 生成文件名 (例如: 2026-02-06_NVDA_决策备忘.md)
    date_str = datetime.now().strftime("%Y-%m-%d")
    clean_title = case_data['title'].replace("/", "_").replace(" ", "_")
    filename = f"{date_str}_{clean_title}.md"
    full_path = os.path.join(OBSIDIAN_PATH, filename)
    
    # 2. 生成 Markdown 内容 (Beancount 风格标签)
    content = f"""---
id: {case_data['id']}
date: {date_str}
tags: {case_data['tags']}
surprise: {case_data['surprise']}
status: Closed
---

# ⚖️ 决策备忘录: {case_data['title']}

## 1. 核心情报
> {case_data['summary']}

## 2. 侦探报告 (Evidence)
{case_data.get('investigation', '无详细报告')}

## 3. 最终裁决 (Verdict)
**👨‍⚖️ 法官笔记:**
{decision_note}

---
*Generated by YangYun AI System*
"""

    # 3. 写入文件
    try:
        # 确保目录存在
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        with open(full_path, "w", encoding="utf-8") as f:
            f.write(content)
        return True, full_path
    except Exception as e:
        return False, str(e)